export const tracks = [
  {
    id: 0,
    post: "",
    title: "Brahms: St Anthony Chorale - Theme, Two Pianos Op.56b",
    genre: "Pop",
    singer: "bc dfnagf mnsdef ",
    url: "https://www.mfiles.co.uk/mp3-downloads/brahms-st-anthony-chorale-theme-two-pianos.mp3",
    duration: 487,
  },
  {
    id: 1,
    post: "",
    title: "Franz Schubert's Ständchen - Voice (Clarinet) & Piano",
    genre: "Rock",
    singer: "gdfbhenb  erdsgbv",
    url: "https://www.mfiles.co.uk/mp3-downloads/franz-schubert-standchen-serenade.mp3",
    duration: 280,
  },
  {
    id: 2,
    post: "",
    title: "Brahms: St Anthony Chorale - Theme, Two Pianos Op.56b",
    genre: "Rap",
    singer: "",
    url: "https://www.mfiles.co.uk/mp3-downloads/brahms-st-anthony-chorale-theme-two-pianos.mp3",
    duration: 367,
  },
  {
    id: 3,
    post: "",
    title: "Franz Schubert's Ständchen - Voice (Clarinet) & Piano",
    genre: "Rock",
    singer: "",
    url: "https://www.mfiles.co.uk/mp3-downloads/franz-schubert-standchen-serenade.mp3",
    duration: 312,
  },
  {
    id: 4,
    post: "",
    title: "Brahms: St Anthony Chorale - Theme, Two Pianos Op.56b",
    genre: "Pop",
    singer: "",
    url: "https://www.mfiles.co.uk/mp3-downloads/brahms-st-anthony-chorale-theme-two-pianos.mp3",
    duration: 240,
  },
  {
    id: 5,
    post: "Rock",
    title: "Franz Schubert's Ständchen - Voice (Clarinet) & Piano",
    genre: "Rock",
    singer: "",
    url: "https://www.mfiles.co.uk/mp3-downloads/franz-schubert-standchen-serenade.mp3",
    duration: 185,
  },
  {
    id: 6,
    post: "",
    title: "Franz Schubert's Ständchen - Voice (Clarinet) & Piano",
    genre: "Rock",
    singer: "",
    url: "https://www.mfiles.co.uk/mp3-downloads/franz-schubert-standchen-serenade.mp3",
    duration: 123,
  },
  {
    id: 7,
    post: "",
    title: "Franz Schubert's Ständchen - Voice (Clarinet) & Piano",
    genre: "Rock",
    singer: "",
    url: "https://www.mfiles.co.uk/mp3-downloads/franz-schubert-standchen-serenade.mp3",
    duration: 240,
  },
];
